[package]
name = "consensus-client"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "consensus-client"
path = "src/main.rs"


[dependencies]
#Mysticeti
consensus-core = { git = "https://github.com/scalarorg/mysticeti.git", package = "consensus-core" }
consensus-config = { git = "https://github.com/scalarorg/mysticeti.git", package = "consensus-config" }
mysten-metrics = { git = "https://github.com/MystenLabs/sui", rev = "c58d2a0bfaae04581c56510548194524e89e2888", package = "mysten-metrics"}
sui-protocol-config = { git = "https://github.com/MystenLabs/sui", rev = "c58d2a0bfaae04581c56510548194524e89e2888", package = "sui-protocol-config"}
alloy-primitives = { version = "1.3.0", default-features = false, features = ["map-foldhash"] }
alloy-rpc-types-engine = { version = "1.0.23", default-features = false }
# reth-engine-primitives = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.6.0", package = "reth-engine-primitives" }
reth-ethereum-engine-primitives = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.6.0", package = "reth-ethereum-engine-primitives" }
reth-rpc-api = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.6.0", package = "reth-rpc-api", features=["client"] }
reth-rpc-layer = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.6.0", package = "reth-rpc-layer" }

tower = { version = "0.5", features = ["full"] }
# pin-project.workspace = true

prometheus = "0.13.3"
derive-getters = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
jsonrpsee = { workspace = true }
clap = { version = "4.0", features = ["derive"] }
tiny-keccak = "2.0.2"

[dev-dependencies]
tokio-test = { workspace = true }
