#!/bin/bash

# Setup script for FastEVM Consensus Client configuration files
# This script copies the node configuration files to the config directory

set -e

# Create config directory if it doesn't exist
mkdir -p config

# Copy node configuration files
echo "Copying node configuration files..."
cp examples/node0.yml config/
cp examples/node1.yml config/
cp examples/node2.yml config/
cp examples/node3.yml config/

# Copy committee configuration example (will be generated by init container)
cp examples/committees.yml config/

echo "Configuration files copied to config/ directory:"
ls -la config/

echo ""
echo "Setup complete! You can now run:"
echo "docker-compose up -d"
echo ""
echo "The init container will generate a new committee.yml file,"
echo "and all 4 nodes will start using their respective config files."
