[package]
name = "fastevm-execution"
version = "0.1.0"
edition = "2021"

[lib]
name = "fastevm_execution"
path = "src/lib.rs"

[[bin]]
name = "fastevm-execution"
path = "src/main.rs"

# [[bin]]
# name = "cli"
# path = "src/cli.rs"

# [[bin]]
# name = "fastevm-bench"
# path = "tests/bench/main.rs"

[dependencies]
# reth-extension = { workspace = true }
rpc-shared-api = { workspace = true }
gravity-api-types = { workspace = true }
# Ethereum
alloy-primitives = { workspace = true, default-features = false, features = ["map-foldhash"] }
alloy-rpc-types-engine = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
alloy-consensus = { workspace = true }
alloy-eips = { workspace = true }
# alloy-evm = { workspace = true }

alloy-rlp = { workspace = true }
# alloy = { workspace = true, features = ["network", "rpc"] }
# alloy-signer-local = { workspace = true }

eyre = { workspace = true}
futures-util = { workspace = true}
tracing = { workspace = true }
clap = "4"  
hex = { workspace = true }
# Gravity
greth = { workspace = true }
# reth-pipe-exec-layer-event-bus = { workspace = true }
# Reth
reth-basic-payload-builder = { workspace = true }
reth-chainspec = { workspace = true }
reth-ethereum = { workspace = true }
reth-ethereum-engine-primitives = { workspace = true }
reth-ethereum-payload-builder = { workspace = true }
reth-evm = { workspace = true }
# reth-primitives-traits = { workspace = true }
reth-provider = { workspace = true }
reth-revm = { workspace = true }
# reth-rpc-layer = { workspace = true }
reth-transaction-pool = { workspace = true }
reth-tracing = { workspace = true }
# reth-db-api = { workspace = true }
reth-node-api = { workspace = true }
reth-node-builder = { workspace = true }
# reth-db = { workspace = true, features = ["mdbx"] }
reth-payload-builder = { workspace = true }
revm = { workspace = true }

# Customize execution
# reth-cli-runner = { workspace = true }
# reth-ethereum-cli = { workspace = true, default-features = false }
# reth-fs-util = { workspace = true }
# reth-libmdbx = { workspace = true }
# reth-metrics = { workspace = true }
# reth-node-core = { workspace = true }
# reth-storage-errors = { workspace = true }

# Additional dependencies for RPC and caching
jsonrpsee = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
# page_size = { workspace = true }
async-trait = { workspace = true }
tokio-stream = "0.1.11"
parking_lot = { workspace = true }
# metrics = { workspace = true }

# Dependencies for mnemonic and account generation
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
# thiserror = { workspace = true }
# Consensus dependencies
# consensus-core = { workspace = true }
# auto_impl.workspace = true
# strum = { workspace = true }
# sysinfo = { workspace = true }


# For cli
# reth-network-peers = { workspace = true }
# bip39 = "2.0"
# hdwallet = "0.3"
# reqwest = { version = "0.12", features = ["json"] }
# secp256k1 = { workspace = true }
# sha2 = { version = "0.10", default-features = false }
# End for cli

[dev-dependencies]
tokio-test = { workspace = true }
tempfile = "3"
http = { workspace = true }
metrics = { workspace = true }
assert_matches = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-network = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
# sha2 = { version = "0.10", default-features = false }
reqwest = { version = "0.12", features = ["json"] }

# gravity_bench - Transaction generator for benchmarking
gravity_bench = { git = "https://github.com/Galxe/gravity_bench.git", branch = "main" }

[features]
default = []
bench = []